kmgh_user:
    resource: "@KMGHUserBundle/Controller/"
    type:     annotation
    prefix:   /

kmgh_app:
    resource: "@KMGHAppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"