<?php

namespace KMGH\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributionRepository extends EntityRepository
{
}
