<?php

namespace KMGH\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends EntityRepository
{
    public function findDiplomeByTypeDiplomeId($id)
    {
        $qb = $this->createQueryBuilder('d')
            ->where('d.typeDiplome = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
