<?php

namespace KMGH\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends EntityRepository
{
    /**
     * Permet de récupéer un ensemble de diplomes correspondant à un TypeDiplome donné passé en paramètre.
     *
     * @param $typeDiplome
     *
     * @return array liste des diplomes
     */
    public function findDiplomeByTypeDiplomeId(TypeDiplome $typeDiplome)
    {
        $qb = $this->createQueryBuilder('d')
            ->where('d.typeDiplome = :diplome')
            ->setParameter('diplome', $typeDiplome);

        return $qb->getQuery()->getResult();
    }
}
